name: ""
description: "My jeklly test"

url: "[YOUR DOMAIN]"

paginate: 10

##markdown: rdiscount
#permalink: pretty
#pygments: true

safe: true
future:      true
lsi:         false
##pygments:  false
highlighter: pygments
markdown:    Kramdown ### maruku
permalink:   date

gravatar: 92f354b0a3a11920792f1075bf067308
email: me@localhost.com
web: 
twitter: 
github: wenqing

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style



